export async function fetchPools(){
  // Simulate network delay
  await new Promise((resolve) => setTimeout(resolve, 1500))

  return [
    {
      id: "1",
      name: "Save America Pool",
      bannerImage: "/placeholder.svg?height=400&width=800&text=America",
      profileImage: "/placeholder.svg?height=56&width=56&text=A",
      isActive: true,
      stakeToken: "TRUMP",
      earnToken: "TRUMP",
      totalStaked: 92019.0,
      apy: "8625.77",
      rewards: 134019.0,
      endsIn: "6d 3h 54m",
    },
    {
      id: "2",
      name: "JIZ Pool",
      bannerImage: "/placeholder.svg?height=400&width=800&text=JIZ",
      profileImage: "/placeholder.svg?height=56&width=56&text=J",
      isActive: true,
      stakeToken: "JIZ",
      earnToken: "JIZ",
      totalStaked: 69100.0,
      apy: "90820.40",
      rewards: 1069100.0,
      endsIn: "6d 5h 13m",
    },
    {
      id: "3",
      name: "Alotta Dixin!!!",
      bannerImage: "/placeholder.svg?height=400&width=800&text=DIX",
      profileImage: "/placeholder.svg?height=56&width=56&text=D",
      isActive: true,
      stakeToken: "DIX",
      earnToken: "DIX",
      totalStaked: 12000000.0,
      apy: "8275.37",
      rewards: 18900000.0,
      endsIn: "6d 22h 43m",
    },
    {
      id: "4",
      name: "Live Wen Ser Staking",
      bannerImage: "/placeholder.svg?height=400&width=800&text=WENSER",
      profileImage: "/placeholder.svg?height=56&width=56&text=W",
      isActive: true,
      stakeToken: "WENSER",
      earnToken: "WENSER",
      totalStaked: 1000.0,
      apy: "152947.40",
      rewards: 1000992.0,
      endsIn: "238d 21h 8m",
    },
    {
      id: "5",
      name: "Bit Bird",
      bannerImage: "/placeholder.svg?height=400&width=800&text=BIRD",
      profileImage: "/placeholder.svg?height=56&width=56&text=B",
      isActive: true,
      stakeToken: "TST",
      earnToken: "TST",
      totalStaked: 10000.0,
      apy: "12084.15",
      rewards: 1009993.0,
      endsIn: "3d 12h 45m",
    },
    {
      id: "6",
      name: "Ended Pool Example",
      bannerImage: "/placeholder.svg?height=400&width=800&text=ENDED",
      profileImage: "/placeholder.svg?height=56&width=56&text=E",
      isActive: false,
      stakeToken: "END",
      earnToken: "END",
      totalStaked: 50000.0,
      apy: "0.00",
      rewards: 75000.0,
      endsIn: "0d 0h 0m",
    },
  ]
}
